version: '3'

services:
  pmm-server:
    image: percona/pmm-server:2
    hostname: pmm-server
    container_name: pmm-server
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "8282:80"
      - "8383:443"
      - "9000:9000"
      - "8123:8123"
    volumes:
      - pmm-server-data:/srv
  pmmi-server:
    image: percona/pmm-server:2
    hostname: pmmi-server
    container_name: pmmi-server
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "8284:80"
      - "8385:443"
      - "9002:9000"
      - "8125:8123"
    volumes:
      - pmmi-server-data:/srv
  pmm-client:
    image: percona/pmm-client:2
    hostname: pmm-client
    container_name: pmm-client
    restart: always
    ports:
      - "42000:42000"
      - "42001:42001"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - pmm-server
    volumes:
      - ./setup/pmm/agent.yaml:/etc/pmm-agent.yaml
      - pmm-client-data:/srv
    environment:
      - PMM_AGENT_CONFIG_FILE=/etc/pmm-agent.yaml
      - PMM_AGENT_SERVER_USERNAME=admin
      - PMM_AGENT_SERVER_PASSWORD=admin
      - PMM_AGENT_SERVER_ADDRESS=pmm-server:443
      - PMM_AGENT_SERVER_INSECURE_TLS=true
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./setup/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
#      - ./setup/mongo/db:/data/db
      - mongodb-data:/data/db
      - ./setup/mongo/mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    command: ["--config", "/etc/mongod.conf"]
  mongodb2:
    image: mongo
    container_name: mongodb2
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./setup/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
      #      - ./setup/mongo/db:/data/db
      - mongodb2-data:/data/db
      - ./setup/mongo/mongod.conf:/etc/mongod.conf
    ports:
      - 27018:27017
    command: [ "--config", "/etc/mongod.conf" ]
  mongodb3:
    image: mongo
    container_name: mongodb3
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./setup/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
      #      - ./setup/mongo/db:/data/db
      - mongodb3-data:/data/db
      - ./setup/mongo/mongod.conf:/etc/mongod.conf
    ports:
      - 27019:27017
    command: [ "--config", "/etc/mongod.conf" ]

volumes:
  pmm-server-data:
  pmmi-server-data:
  pmm-client-data:
  mongodb-data:
  mongodb2-data:
  mongodb3-data:
